version: "3.7"

services:
  proxy:
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./back.conf:/etc/nginx/back.conf
      - ./front.conf:/etc/nginx/front.conf
    ports:
      - "80:80"
      - "443:443"

  front:
    image: front
    restart: always

  back:
    image: back
    restart: always
    env_file:
      - back.env

  mongo:
    image: mongo
    restart: always
    env_file:
      - mongo.env
    volumes:
      - ./data/db:/data/db
